### ISSUE TITLE
nominate 2015 keynoters

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#144] opened 2014-12-11 21:49 UTC

**Comment by JackDanger** [comment] 2015-01-21 00:44
I'd like to nominate @cczona for her extremely practical work in engineering diversity. I think she has that right balance of speaking about things that are relevant but from a perspective that's pretty far from how most audience members have approached it before.

**Comment by eglute** [comment] 2015-01-21 01:58
I would also like to nominate Carina C. Zona, @cczona.
Carina is a great speaker with a strong development and technical background. In addition to speaking about technology, she has also given talks about:
* diversity-inclusive data modeling
* socioeconomic/class issues in tech
* SF gentrification & start up scene
* local effects of the "sharing economy" on communities
* the business value of intentionally recruiting engineers who don't arise from formal CS background
tactics for in-real-life tech community building

Carina is also the heart and mind behind CallbackWomen, which helps conferences promote their calls for proposals to technical women.

**Comment by jenmyers** [comment] 2015-01-21 13:32
I had planned to also nominate @cczona, but it looks like I've been beat to it twice! Let me add my vote to the list. She has a strong message, a lot of speaking experience and gives tirelessly to the community. I really can't think of many better candidates.

**Comment by brainwane** [comment] 2015-01-21 13:43
I nominate [Erik Moeller](https://meta.wikimedia.org/wiki/User:Erik_Moeller_%28WMF%29), who works on product and strategy at the Wikimedia Foundation, was one of the people who created Wikimedia Commons and the Definition of Free Cultural Works, and is a longtime free software and free culture advocate. His talk at Wikimania 2013, ["Ghosts of Wikis Yet to Come: Three Stories of Wikimedia's Future"](https://wikimania2013.wikimedia.org/wiki/Submissions/Ghosts_of_Wikis_Yet_to_Come:_Three_Stories_of_Wikimedia%27s_Future), was a particularly imaginative and thought-provoking set of hypotheticals ([video](https://www.youtube.com/watch?v=9wKZzq75Db8)). I think he's never been to OSBridge, and I would love to hear his perspective -- perhaps about Wikimedia's and Wikipedia's lessons learned for the larger open source community.

**Comment by jameysharp** [comment] 2015-01-21 17:59
After reading his [AMA](https://www.reddit.com/r/IAmA/comments/2syfmu/happy_mlk_day_iama_black_computer_scientist_who/) this week, I was thinking that it would be awesome to have James Mickens as an Open Source Bridge keynote speaker.

**Comment by cczona** [comment] 2015-01-21 18:48
Thanks! 

@lhawthorn just gave a talk, "Check Your Privilege", at LCA that was tremendously well received, both as content and inspiration. I want to hear more of whatever she'd like to say.

@kelseyq has been doing important educational work in both the SF bay area tech community and the area's general local community, on the effects of tech work on urban politics, gentrification, and community ties. She pushes back on the assumption that programming is apolitical. Her talks are entertaining, while challenging us to think much harder about what the influence we weild -- for better & worse, intentional & not --  in shaping the local communities we inhabit. e.g.

  * http://nerd.kelseyinnis.com/blog/2014/12/19/your-job-is-political-tech-money-in-politics/
  * https://modelviewculture.com/pieces/tech-workers-and-the-eviction-crisis (JSFest)

She's also one of the founders of Lambda Ladies http://www.lambdaladies.com/2013/05/04/the-lambda-ladies-story/

**Comment by coderanger** [comment] 2015-01-21 19:38
+1 on @cczona!

**Comment by zspencer** [comment] 2015-01-22 19:14
+1 on @cczona, her schema's for the real world talk breaks down a lot of the misconceptions we have around database normalization and creating user interfaces that match how the world actually works.

I'd also recommend Adria Richards, whose been doing some incredible behind-the-scenes work around harassment response and inclusive tech spaces.

**Comment by rahaeli** [comment] 2015-01-27 06:40
I'd actually like to throw my own hat in: I have a talk I've given at a few conferences, called "Be Kind To Your Hands, You'll Miss Them When They're Gone", about repetitive stress injuries: how to spot them, what they look like, warning symptoms that you shouldn't ignore, and how to prevent them (or, let's be honest, how to postpone them for as long as you can). As someone who's currently up to five separate surgeries to treat RSI-related issues brought about by my own bad habits, it's something I'm incredibly passionate about, because I see so many of those bad habits proliferating in my fellow nerds. I'd love a chance to get the message out more widely.

**Comment by vmbrasseur** [comment] 2015-01-28 04:09
I nominate @webchick. For those unfortunate not to have met or seen her speak yet, here's her [Drupal Association Board bio](https://assoc.drupal.org/about/board):

> Angela Byron, Director of Community Development at Acquia, is a Drupal core co-maintainer, recipient of the Google-O'Reilly Open 2008 Source Award for Best Contributor, co-author of the O'Reilly book Using Drupal, and an open source evangelist who lives and breathes Drupal. She got her start as a Google Summer of Code student in 2005 and since then has completely immersed herself in contributing to open source. Her work includes core patch review, improving the user experience of Drupal through the Spark project, testing and quality assurance efforts, improving and fixing documentation, and general community cat herding.

Angie is a kind and thoughtful person, and an accomplished speaker who's able to communicate wonderfully. She has years of experience in community management and brilliant insights thanks to her experience. I think her perspective and knowledge would be a valuable addition to the 2015 edition of OSBridge.

**Comment by capnleela** [comment] 2015-02-01 10:54
I'd like to nominate a few people. 
* Walidah Imarisha [@walidahimarisha](https://twitter.com/WalidahImarisha) who recently gave a talk on how community organizers are really science fiction creators because they imagine different versions of the world
* Tiffany Mikell [@mikellsolution](https://twitter.com/mikellsolution) Co-founder of [@blackstarlaunch](https://twitter.com/blackstarlaunch)
* Jen-Mei Wu [@jenmeiwu](https://twitter.com/jenmeiwu) founded the Oakland-based LOL MakerSpace
* David Huerta [@huertanix](https://twitter.com/huertanix) does hardware hacks and runs in the OHS crowd

**Comment by zspencer** [comment] 2015-02-01 18:57
+1 to both @mikellsolution and @jenmeiwu. I've had really great and
informative interactions with both of them.

**Comment by breedx2** [comment] 2015-02-02 08:10
@joegrand is a recent pdx transplant, one of the most talented hardware hackers in the nation (serious ninja level+++), a geek TV celebrity, public speaker, hackaday prize judge, early member (founder?) of probably the first American hackerspace, and he's one of the most sincere, nice, engaging, and genuine people to know.  It would be a shame not to have him keynote at OSB2015.

**Comment by capnleela** [comment] 2015-02-03 00:36
I'd also like to nominate Kronda Adair [@kronda](https://twitter.com/kronda) as a keynote. The [talk she submitted](http://opensourcebridge.org/proposals/1471) for the CFP would be amazing.

**Comment by 1337807** [comment] 2015-02-03 01:07
+100 for Kronda, she's amazing.

**Comment by shawnacscott** [comment] 2015-02-03 02:57
Totally agree on Kronda. Her talk last year was amazing and insightful, and she's just generally a kick ass person and speaker.

**Comment by brainwane** [comment] 2015-02-04 18:19
What great nominations! Cool! Thanks!

The nomination period is now over (the nomination period [closed January 31](http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/)), so I'm taking the initiative to close this issue; the conference chairs (and, I presume, the content committee) will review the public nominations, as well as nominations that have been emailed to them privately, and choose and invite keynote speakers. I've created a new task for that: #175.

Thanks to everyone who nominated!

**Comment by shawnacscott** [comment] 2015-02-05 08:31
Reopening for one last round!

**Comment by shawnacscott** [comment] 2015-02-05 08:40
I'd like to +1 Walidah Imarisha. 

I'd also like to nominate Kortney Ziegler, founder of Trans*H4ck. ([@fakerapper](http://twitter.com/fakerapper))

Bio from his SXSW appearance: 

>Kortney Ryan Ziegler is an award winning artist, writer, and the first person to hold the Ph.D. of African American Studies from Northwestern University.

>He is the founder of Trans*H4CK a hackathon and speaker series that spotlights transgender created tech and startups and cofounder of BlackStarMedia a platform that provides entrepreneurial resources for people of color.

**Comment by capnleela** [comment] 2015-02-06 03:06
I'd like to +1 Kortney Ziegler.

**Comment by mtitolo** [comment] 2015-02-06 04:30
+1 to both @kelseyq and @cczona

**Comment by lehudgins** [comment] 2015-02-12 21:32
Definitely excited about Kronda!!!!!, Sharon Steed, and Walidah Imarisha.

**Comment by christi3k** [comment] 2015-02-13 19:03
Via email, we received nominations for these folks not already listed in this bug:

Sarah Sharp
Paul Fenwick
Stephanie Morillo
Liz Henry
Allison Parrish

If you'd like to +1 any of them, please do so.

**Comment by 1337807** [comment] 2015-02-13 19:10
+1 Stephanie Morillo!

**Comment by cczona** [comment] 2015-02-13 19:20
+1 Sarah Sharp and Liz Henry!

**Comment by shawnacscott** [comment] 2015-02-13 23:10
+1 for

**Comment by joshtriplett** [comment] 2015-02-14 00:11
+1 to Sarah Sharp. She's an extraordinary, captivating speaker on a wide variety of topics, including several that have been mentioned as key anchors of OSBridge.

+1 to Paul Fenwick. He takes serious topics and presents them in both an engaging and comedic manner.

**Comment by kronda** [comment] 2015-02-14 02:41
+1 Walidah Imarisha and Sharon Steed. And thanks for the votes!

**Comment by bkerensa** [comment] 2015-02-17 18:29
Not sure if there is time for more +1's but:

+1 Liz Henry
+1 Kronda
+1 Sarah Sharp

**Comment by christi3k** [comment] 2015-02-27 19:05
Just a quick note to let everyone know we've selected three speakers to invite from this awesome list of nominations. Per #191 I've invited those three and we'll update this issue when we've confirmed with everyone.

**Closed by christi3k** 2015-02-27 19:05 UTC
